### PR TITLE
README: Drop unnecessary trailing slash in URL

### PR DESCRIPTION
**Pull request by Lin-Buo-Ren**
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

### CODE REVIEW

**Comment by Lin-Buo-Ren** [comment]
Not noticing the project not accepting patches via GitHub PRs, apologies.

**Comment by EnderNightLord-ChromeBook** [comment]
Hey ... Wait... Who said nobody could make a PR...

Hello. I'm endernightlord... And I'm the creator.

**Comment by Lin-Buo-Ren** [comment]
> Hey ... Wait... Who said nobody could make a PR...

I misinterpreted the <https://github.com/dahlia-os/zircon/blob/master/docs/contributing.md#process>, which came from Google and surely has a different contributing policy.

**Comment by EnderNightLord-ChromeBook** [comment]
Thanks

**Pull request merged**
